// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD68G4_-LphgA6Mc1HJFn6Y5DaS13Zvv-c',
    appId: '1:64235358220:web:4499f4ba4253552d8b4629',
    messagingSenderId: '64235358220',
    projectId: 'incrat-academy',
    authDomain: 'incrat-academy.firebaseapp.com',
    storageBucket: 'incrat-academy.firebasestorage.app',
    measurementId: 'G-XGTSNPPQN0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvl9Agpl6wQLGhukgaTGEIvECndgH2r-k',
    appId: '1:64235358220:android:2a7d7ec254d1a3a28b4629',
    messagingSenderId: '64235358220',
    projectId: 'incrat-academy',
    storageBucket: 'incrat-academy.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVVJYeQZZHbVxCJU5jXYjR2n609vofZUE',
    appId: '1:64235358220:ios:96552e147b51e1428b4629',
    messagingSenderId: '64235358220',
    projectId: 'incrat-academy',
    storageBucket: 'incrat-academy.firebasestorage.app',
    androidClientId: '64235358220-cr9a8m8l36h0lu15hhdgrfvbikfrgatt.apps.googleusercontent.com',
    iosClientId: '64235358220-me5k9d1qv9ldml6fv9kcr9cgoi6uft2e.apps.googleusercontent.com',
    iosBundleId: 'academy.incrat.com',
  );

}